version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-hrp
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: gpsc_hrp_db
      MYSQL_USER: hrpuser
      MYSQL_PASSWORD: hrp123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  
volumes:
  mysql-data: